---
- name: Create a Firewall Rule for SNMP Traffic
  hosts: all
  become: yes
  gather_facts: true
  vars:
  - ansible_connection: paramiko_ssh

  tasks:

  - name: Create a Firewall Rule (Ubuntu)
    when: ansible_facts['os_family'] == "Debian"
    ufw:
      rule: allow
      port: snmp
      state: enabled

  - name: Create a Firewall Rule (RHEL, Suse, Alma)
    when: ansible_facts['os_family'] == "RedHat" or
          ansible_facts['os_family'] == "Suse" or
          ansible_facts['os_family'] == "AlmaLinux"
    shell: firewall-cmd --permanent --zone=public --add-rich-rule='rule family="ipv4" source address=""{{ tunnel_ip }}"/32" port port="161" protocol="udp" accept'
    notify:
    - Restart firewalld

  handlers:
    - name: Restart firewalld
      service:
        name: "firewalld"
        state: restarted